/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.screens;

import com.formdev.flatlaf.FlatLaf;
import org.example.DatabaseConnector;
import org.example.models.User;
import org.example.models.UserShop;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author user
 */
public class AccountFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AccountFrame.class.getName());

    private User currentUser ;
    private FlatLaf theme;
    private final DatabaseConnector connector;
    private AccountController controller ;
    /**
     * Creates new form AccountFrame
     */
    public AccountFrame(User currentUser , FlatLaf theme, DatabaseConnector connector) {
        this.connector = connector;
        controller = new AccountController( connector, currentUser );
        this.theme = theme;
        this.currentUser = currentUser;
        initComponents();
        initData();
    }

    private void clearShopInputForm() {
                ShopNameLabel.setText("");
                ShopTypeLabel.setText("");
                ShopAdrsLabel.setText("");
                ShopPhoneLabel.setText("");
                ShopEmailLabel.setText("");
                ShopStatusLabel.setText("");
    }

    private void initData() {
        UserNameLabel.setText(currentUser.getUser_name());
        UserEmailLabel.setText(currentUser.getEmail());

        List<UserShop> myshops = controller.getMyShops();

        if(myshops.isEmpty()) {
            System.out.println("Empty shops");
        } else {
            DefaultListModel<String> listModel = new DefaultListModel<>();
            myshops.forEach( e->{
                listModel.addElement(e.getName());
            });
            MyShopeListView.setModel(listModel);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserNameLabel = new javax.swing.JLabel();
        UserEmailLabel = new javax.swing.JLabel();
        OpenAShopBtn = new javax.swing.JLabel();
        ViewShopPanel = new javax.swing.JPanel();
        ShopDetailForm = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MyShopeListView = new javax.swing.JList<>();
        AddShopForm = new javax.swing.JPanel();
        ShopNameLabel = new javax.swing.JTextField();
        ShopTypeLabel = new javax.swing.JTextField();
        ShopAdrsLabel = new javax.swing.JTextField();
        ShopPhoneLabel = new javax.swing.JTextField();
        ShopEmailLabel = new javax.swing.JTextField();
        ShopStatusLabel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AddShopBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UserNameLabel.setFont(new java.awt.Font("Samsung Sharp Sans", 1, 24)); // NOI18N
        UserNameLabel.setText("Name");

        UserEmailLabel.setText("user@gmail.com");

        OpenAShopBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        OpenAShopBtn.setForeground(new java.awt.Color(51, 204, 255));
        OpenAShopBtn.setText("Create a new shop");
        OpenAShopBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpenAShopBtnMouseClicked(evt);
            }
        });

        ViewShopPanel.setLayout(new java.awt.CardLayout());

        jScrollPane1.setBorder(null);

        MyShopeListView.setBorder(null);
        jScrollPane1.setViewportView(MyShopeListView);

        javax.swing.GroupLayout ShopDetailFormLayout = new javax.swing.GroupLayout(ShopDetailForm);
        ShopDetailForm.setLayout(ShopDetailFormLayout);
        ShopDetailFormLayout.setHorizontalGroup(
            ShopDetailFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShopDetailFormLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        ShopDetailFormLayout.setVerticalGroup(
            ShopDetailFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShopDetailFormLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        ViewShopPanel.add(ShopDetailForm, "card3");
        ShopDetailForm.getAccessibleContext().setAccessibleName("");

        jLabel1.setText("Shop Name:");

        jLabel2.setText("Shop Type");

        jLabel3.setText("Address");

        jLabel4.setText("Phone Number");

        jLabel5.setText("Business Email");

        jLabel6.setText("Status");

        AddShopBtn.setBackground(new java.awt.Color(102, 204, 255));
        AddShopBtn.setText("Done");
        AddShopBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddShopBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddShopFormLayout = new javax.swing.GroupLayout(AddShopForm);
        AddShopForm.setLayout(AddShopFormLayout);
        AddShopFormLayout.setHorizontalGroup(
            AddShopFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddShopFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddShopFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AddShopFormLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddShopFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ShopNameLabel)
                    .addComponent(ShopTypeLabel)
                    .addComponent(ShopAdrsLabel)
                    .addComponent(ShopPhoneLabel)
                    .addComponent(ShopEmailLabel)
                    .addComponent(ShopStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
            .addGroup(AddShopFormLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddShopBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddShopFormLayout.setVerticalGroup(
            AddShopFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddShopFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddShopFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShopNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(AddShopFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShopTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(AddShopFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShopAdrsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(AddShopFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShopPhoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(AddShopFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShopEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(AddShopFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShopStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(AddShopBtn)
                .addGap(20, 20, 20))
        );

        ViewShopPanel.add(AddShopForm, "ADDSHOPCARD");
        AddShopForm.getAccessibleContext().setAccessibleName("ADDSHOPCARD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OpenAShopBtn)
                    .addComponent(ViewShopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(UserNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UserEmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(UserNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserEmailLabel)
                .addGap(249, 249, 249)
                .addComponent(OpenAShopBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewShopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OpenAShopBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpenAShopBtnMouseClicked
        // TODO add your handling code here:
         CardLayout cardLayout = (CardLayout) ViewShopPanel.getLayout();
         cardLayout.show(ViewShopPanel,"ADDSHOPCARD");

        
    }//GEN-LAST:event_OpenAShopBtnMouseClicked

    private void AddShopBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddShopBtnActionPerformed
        // TODO add your handling code here:
        UserShop newShop = new UserShop(0,ShopNameLabel.getText().trim(),
                currentUser.getId(),
                ShopTypeLabel.getText().trim(),
                ShopAdrsLabel.getText().trim(),
                ShopPhoneLabel.getText().trim(),
                ShopEmailLabel.getText().trim(),
                ShopStatusLabel.getText().trim()
        );
        if(controller.addShop(newShop)) {
            System.out.println("Opened a shop");
            clearShopInputForm();
            CardLayout cardLayout = (CardLayout) ViewShopPanel.getLayout();
            cardLayout.show(ViewShopPanel,"SHOPDETAILFORM");
        } else {
            System.out.println("Fail opening a shop");
        }

    }//GEN-LAST:event_AddShopBtnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new AccountFrame( new User() ).setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddShopBtn;
    private javax.swing.JPanel AddShopForm;
    private javax.swing.JList<String> MyShopeListView;
    private javax.swing.JLabel OpenAShopBtn;
    private javax.swing.JTextField ShopAdrsLabel;
    private javax.swing.JPanel ShopDetailForm;
    private javax.swing.JTextField ShopEmailLabel;
    private javax.swing.JTextField ShopNameLabel;
    private javax.swing.JTextField ShopPhoneLabel;
    private javax.swing.JTextField ShopStatusLabel;
    private javax.swing.JTextField ShopTypeLabel;
    private javax.swing.JLabel UserEmailLabel;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JPanel ViewShopPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
