/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.screens;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;

/**
 *
 * @author user
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setTitle("Javarket — Dashboard");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Drawer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Content = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 245, 245));

        Drawer.setBackground(new java.awt.Color(240, 240, 240));
        Drawer.setMinimumSize(new java.awt.Dimension(220, 0));
        Drawer.setPreferredSize(new java.awt.Dimension(240, 600));
        Drawer.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 16));
        jLabel2.setText("Navigation");

        jButton1.setText("Home");
        jButton1.setFocusPainted(false);
        jButton1.putClientProperty("JButton.buttonType", "roundRect");

        jButton2.setText("Products");
        jButton2.setFocusPainted(false);
        jButton2.putClientProperty("JButton.buttonType", "roundRect");

        jButton3.setText("Settings");
        jButton3.setFocusPainted(false);
        jButton3.putClientProperty("JButton.buttonType", "roundRect");

        javax.swing.GroupLayout DrawerLayout = new javax.swing.GroupLayout(Drawer);
        Drawer.setLayout(DrawerLayout);
        DrawerLayout.setHorizontalGroup(
            DrawerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DrawerLayout.createSequentialGroup()
                .addGroup(DrawerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DrawerLayout.setVerticalGroup(
            DrawerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DrawerLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(16, 16, 16)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(455, Short.MAX_VALUE))
        );

        getContentPane().add(Drawer, java.awt.BorderLayout.WEST);

        Content.setBackground(new java.awt.Color(255, 255, 255));
        Content.setBorder(javax.swing.BorderFactory.createEmptyBorder(24, 24, 24, 24));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 20));
        jLabel1.setText("Welcome to Javarket");

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(Content, java.awt.BorderLayout.CENTER);
        Content.getAccessibleContext().setAccessibleName("");
        Content.getAccessibleContext().setAccessibleDescription("");

        pack();
        setMinimumSize(new java.awt.Dimension(900, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            FlatLaf.setup(new FlatMacLightLaf());
            javax.swing.UIManager.put("Component.focusWidth", 1);
            javax.swing.UIManager.put("Component.arc", 12);
            javax.swing.UIManager.put("Button.arc", 12);
            javax.swing.UIManager.put("TextComponent.arc", 12);
            javax.swing.UIManager.put("Component.accentColor", "#2F80ED");
            com.formdev.flatlaf.FlatLaf.setUseNativeWindowDecorations(true);
        } catch (Exception ignore) {
        }
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Drawer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
