/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.screens;

import javax.swing.*;
import java.awt.*;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;

/**
 *
 * @author user
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private AppController controller;
    private JPanel shopWindow;
    private ShopPanel shopPanel;
    private CartPanel cartPanel;
    private HistoryPanel historyPanel;
    private CardLayout cardLayout;
    private boolean isDarkTheme = false;
    /**
     * Creates new form MainFramex
     */
    public MainFrame( AppController controller ) {
        this.controller = controller;
        initComponents();
        init();
    }

    private void init() {
        loadPanels();
        showShopPanel();
    }

    private void loadPanels() {
        // Create shop panel directly
        shopPanel = new ShopPanel();
        
        // Create cart panel
        cartPanel = new CartPanel();
        
        // Create history panel with controller to filter by current user
        historyPanel = new HistoryPanel(controller);
        
        // Add panels to content with CardLayout
        Content.add(shopPanel, "SHOP");
        Content.add(cartPanel, "CART");
        Content.add(historyPanel, "HISTORY");
    }
    
    private void showShopPanel() {
        cardLayout = (CardLayout) Content.getLayout();
        cardLayout.show(Content, "SHOP");
        Content.revalidate();
        Content.repaint();
    }
    
    private void showCartPanel() {
        cartPanel.refreshCart();
        cardLayout = (CardLayout) Content.getLayout();
        cardLayout.show(Content, "CART");
        Content.revalidate();
        Content.repaint();
    }
    
    private void showHistoryPanel() {
        historyPanel.refreshHistory();
        cardLayout = (CardLayout) Content.getLayout();
        cardLayout.show(Content, "HISTORY");
        Content.revalidate();
        Content.repaint();
    }

    @Override
    public void frameInit() {
        super.frameInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        Drawer = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        themeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));

        Content.setLayout(new java.awt.CardLayout());
        Content.setOpaque(true);
        getContentPane().add(Content, java.awt.BorderLayout.CENTER);
        Content.getAccessibleContext().setAccessibleName("");
        Content.getAccessibleContext().setAccessibleDescription("");

        Drawer.setMinimumSize(new java.awt.Dimension(200, 0));
        Drawer.setPreferredSize(new java.awt.Dimension(200, 600));
        Drawer.setOpaque(true);

        jButton1.setText("Shop");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cart");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("History");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Account");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DrawerLayout = new javax.swing.GroupLayout(Drawer);
        Drawer.setLayout(DrawerLayout);
        DrawerLayout.setHorizontalGroup(
            DrawerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DrawerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DrawerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        DrawerLayout.setVerticalGroup(
            DrawerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DrawerLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addGap(12, 12, 12)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(17, 17, 17))
        );

        getContentPane().add(Drawer, java.awt.BorderLayout.WEST);

        jPanel1.setBackground(new java.awt.Color(113, 163, 255));
        jPanel1.setOpaque(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(928, 50));

        jLabel3.setFont(new java.awt.Font("Samsung Sharp Sans", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("JavarKet");

        themeBtn.setText("Theme");
        themeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(themeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(264, 264, 264)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(419, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(themeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        showShopPanel();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        showCartPanel();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        showHistoryPanel();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            com.formdev.flatlaf.FlatLaf laf = (com.formdev.flatlaf.FlatLaf) javax.swing.UIManager.getLookAndFeel();
            AccountFrame accountFrame = new AccountFrame(controller.getCurrentUser(), laf, controller.getConnector());
            accountFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            accountFrame.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Unable to open Account window: " + ex.getMessage(), "Account", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void themeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themeBtnActionPerformed
        try {
            if (isDarkTheme) {
                UIManager.setLookAndFeel(new FlatMacLightLaf());
                themeBtn.setText("🌙 Dark");
                isDarkTheme = false;
            } else {
                UIManager.setLookAndFeel(new FlatMacDarkLaf());
                themeBtn.setText("☀️ Light");
                isDarkTheme = true;
            }
            
            // 1) Refresh LAF for this frame
            SwingUtilities.updateComponentTreeUI(this);

            // 2) Re-apply container backgrounds immediately after LAF switch
            updateMainFrameBackground();

            // 3) Update panels manually without resetting their styling
            if (shopPanel != null) {
                System.out.println("Updating shop panel theme");
                shopPanel.updateTheme();
            }
            if (cartPanel != null) {
                System.out.println("Updating cart panel theme");
                cartPanel.updateTheme();
            }
            if (historyPanel != null) {
                SwingUtilities.updateComponentTreeUI(historyPanel);
            }
            
            // 4) Reapply custom styling that needs to be theme-aware
            updateThemeAwareStyling();
            
            pack();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Failed to switch theme: " + e.getMessage(), "Theme Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_themeBtnActionPerformed
    
    private void updateMainFrameBackground() {
        // Update the main frame background based on theme
        if (isDarkTheme) {
            getContentPane().setBackground(new Color(45, 45, 45));
            setBackground(new Color(45, 45, 45));
            // Also update the Content panel specifically
            if (Content != null) {
                Content.setBackground(new Color(45, 45, 45));
            }
            // Update the Drawer (sidebar) background
            if (Drawer != null) {
                Drawer.setBackground(new Color(60, 60, 60));
            }
            // Update the header panel background
            if (jPanel1 != null) {
                jPanel1.setBackground(new Color(60, 60, 60));
            }
            System.out.println("Set main frame dark background");
        } else {
            getContentPane().setBackground(new Color(248, 249, 250));
            setBackground(new Color(248, 249, 250));
            // Also update the Content panel specifically
            if (Content != null) {
                Content.setBackground(new Color(248, 249, 250));
            }
            // Update the Drawer (sidebar) background
            if (Drawer != null) {
                Drawer.setBackground(new Color(255, 255, 255));
            }
            // Update the header panel background
            if (jPanel1 != null) {
                jPanel1.setBackground(new Color(52, 58, 64));
            }
            System.out.println("Set main frame light background");
        }
        
        // Force repaint
        getContentPane().revalidate();
        getContentPane().repaint();
        if (Content != null) {
            Content.revalidate();
            Content.repaint();
        }
        if (Drawer != null) {
            Drawer.revalidate();
            Drawer.repaint();
        }
        if (jPanel1 != null) {
            jPanel1.revalidate();
            jPanel1.repaint();
        }
    }
    
    private void updateThemeAwareStyling() {
        // Update navigation buttons styling based on theme
        if (jButton1 != null) updateNavigationButtonStyle(jButton1, "Shop");
        if (jButton2 != null) updateNavigationButtonStyle(jButton2, "Cart");
        if (jButton3 != null) updateNavigationButtonStyle(jButton3, "History");
        if (jButton4 != null) updateNavigationButtonStyle(jButton4, "Account");
    }
    
    private void updateNavigationButtonStyle(JButton button, String text) {
        if (text != null) button.setText(text);
        button.setFont(button.getFont().deriveFont(Font.BOLD, 14f));
        
        if (isDarkTheme) {
            button.setBackground(new Color(45, 45, 45));
            button.setForeground(new Color(255, 255, 255));
        } else {
            button.setBackground(new Color(248, 249, 250));
            button.setForeground(new Color(52, 58, 64));
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Drawer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton themeBtn;
    // End of variables declaration//GEN-END:variables
}
