/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.authenScreens;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.io.InputStream;

/**
 *
 * @author user
 */
public class AuthenScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AuthenScreen.class.getName());

    /**
     * Creates new form AuthenScreen
     */
    public AuthenScreen() {
        try {
            FlatLaf.setup(new FlatMacLightLaf());
            javax.swing.UIManager.put("Component.focusWidth", 1);
            javax.swing.UIManager.put("Component.arc", 12);
            javax.swing.UIManager.put("Button.arc", 12);
            javax.swing.UIManager.put("TextComponent.arc", 12);
            javax.swing.UIManager.put("Component.accentColor", "#2F80ED");
            com.formdev.flatlaf.FlatLaf.setUseNativeWindowDecorations(true);
        } catch (Exception ignore) {
        }
        initComponents();
        setTitle("Javarket — Login");
        setLocationRelativeTo(null);
        EmailField.putClientProperty("JTextField.placeholderText", "Enter your email");
        PasswordField.putClientProperty("JTextField.placeholderText", "Enter your password");
        PasswordField.putClientProperty("JPasswordField.showRevealButton", true);
        LoginBtn.putClientProperty("JButton.buttonType", "roundRect");
        getRootPane().setDefaultButton(LoginBtn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoLabel = new javax.swing.JLabel();
        LoginLabel = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        LoginBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        // Setup logo
        setupLogo();

        LoginLabel.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        LoginLabel.setText("Login");

        EmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Email");

        jLabel3.setText("Password");

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        LoginBtn.setBackground(new java.awt.Color(51, 153, 255));
        LoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        LoginBtn.setText("Login");
        LoginBtn.setFocusPainted(false);
        LoginBtn.setBorderPainted(false);
        LoginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        javax.swing.JPanel contentPanel = new javax.swing.JPanel();
        contentPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(32, 32, 32, 32));
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(logoLabel)
                    .addComponent(LoginLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(EmailField, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addComponent(PasswordField))
                    .addComponent(LoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(logoLabel)
                .addGap(16, 16, 16)
                .addComponent(LoginLabel)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(LoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(contentPanel);
        pack();
        setMinimumSize(new java.awt.Dimension(560, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void EmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailFieldActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        String email = EmailField.getText().trim();
        String password = new String(PasswordField.getPassword());
        
        if (email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both email and password!", "Login Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // TODO: Implement actual authentication
        // For now, just open the main frame
        new org.example.screens.MainFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_LoginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new AuthenScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailField;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel logoLabel;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Setup logo for the login screen
     */
    private void setupLogo() {
        try {
            // Try to load image from resources
            InputStream imageStream = getClass().getClassLoader().getResourceAsStream("images/logo.png");
            if (imageStream != null) {
                ImageIcon originalIcon = new ImageIcon(javax.imageio.ImageIO.read(imageStream));
                // Resize image to fit nicely
                Image originalImage = originalIcon.getImage();
                Image resizedImage = originalImage.getScaledInstance(120, 120, Image.SCALE_SMOOTH);
                ImageIcon resizedIcon = new ImageIcon(resizedImage);
                logoLabel.setIcon(resizedIcon);
                logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            } else {
                // If no image found, create a text-based logo
                logoLabel.setText("🛒 JAVARKET");
                logoLabel.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 28));
                logoLabel.setForeground(new java.awt.Color(51, 153, 255));
                logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            }
        } catch (Exception e) {
            // Fallback to text logo if image loading fails
            logoLabel.setText("🛒 JAVARKET");
            logoLabel.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 28));
            logoLabel.setForeground(new java.awt.Color(51, 153, 255));
            logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            logger.warning("Could not load logo image, using text logo instead: " + e.getMessage());
        }
    }
}
